<?php
/**
 * Mageplace Freshdesk extension
 *
 * @category    Mageplace_Freshdesk
 * @package     Mageplace_Freshdesk
 * @copyright   Copyright (c) 2014 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */

/**
 * @see  Mageplace_Freshdesk_Block_Field_Row
 *
 * @var Mageplace_Freshdesk_Block_Field_Row $this
 */

?>
<li class="wide">
    <div class="field form-group">
        <label for="<?php echo $this->getFieldId(); ?>"
               class="control-label <?php if ($this->isRequired()): ?>required<?php endif; ?>">
            <?php echo $this->getFieldLabel(); ?>
        </label>

        <div class="input-box form-values">
            <?php echo $this->getInputFieldHtml(); ?>
        </div>
    </div>
</li>
