<?php
/**
 * Mageplace Freshdesk extension
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2014 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */

/**
 * @see Mageplace_Freshdesk_Block_Customer_Ticket_View
 * @var Mageplace_Freshdesk_Block_Customer_Ticket_View $this
 */

$_currentUserId = Mage::helper('freshdesk')->getCurrentUser()->getId();
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="freshdesk-ticket">
    <div class="page-title title-buttons">
        <h1><?php echo $this->getTitle(); ?></h1>

        <div class="actions">
            <?php if ($this->isRefreshButtonVisible()): ?>
                <button type="button" title="<?php echo $this->__('Refresh') ?>" class="btn btn-primary btn-refresh-ticket"
                        onclick="location.href='<?php echo $this->getRefreshUrl(); ?>'">
                    <span><span><?php echo $this->__('Refresh') ?></span></span>
                </button>
            <?php endif; ?>
            <button type="button" title="<?php echo $this->__('Create a New Ticket') ?>"
                    class="btn btn-primary btn-create-ticket"
                    onclick="location.href='<?php echo $this->getCreateUrl(); ?>'">
                <span><span><?php echo $this->__('Create a New Ticket') ?></span></span>
            </button>
        </div>
    </div>

    <?php $_ticket = $this->getTicket(); ?>

    <p class="order-date"><?php echo $this->__('Date Created: %s', $this->formatDate($_ticket->getCreatedAt(), 'long')) ?></p>

    <div class="col2-set ticket-info-box">
        <div class="page-title title-buttons notes-box">
            <h1><?php echo $this->getSubject(); ?></h1>

            <div class="actions">
                <button type="button" title="<?php echo $this->__('Reply') ?>"
                        id="ticket_reply_button" class="btn btn-primary btn-close-ticket">
                    <span><span><?php echo $this->__('Reply') ?></span></span>
                </button>
                <?php if ($this->canClose($_ticket)): ?>
                    <button type="button" title="<?php echo $this->__('Close Ticket') ?>"
                            id="ticket_reply_button" class="btn btn-primary btn-close-ticket"
                            onclick="if(confirm('<?php echo $this->__('Are you sure you want to close ticket?'); ?>')) location.href='<?php echo $this->getCloseUrl(); ?>'">
                        <span><span><?php echo $this->__('Close Ticket') ?></span></span>
                    </button>
                <?php endif; ?>
            </div>
        </div>

        <div class="ticket-description">
            <small class="box-date">
                <?php echo $this->getDateDiff($_ticket->getCreatedAt(), $this->__('reported')); ?>
            </small>
            <div class="note-row">
                <?php echo $_ticket->getDescriptionHtml(); ?>
            </div>
        </div>

        <?php foreach ($this->getNotes() as $note) : ?>
            <div class="note-row <?php echo $_currentUserId == $note->getUser()->getId() ? 'current-user' : '';?>">
                <div class="col-1">
                    <div class="box">
                        <div class="box-title">
                            <strong><?php echo $note->getUserName(); ?></strong>
                        </div>
                        <div class="box-date">
                            <?php echo $this->getDateDiff($note->getCreatedAt(), $this->__('said')); ?>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <div class="box-note">
                        <?php echo $note->getBodyHtml(); ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>

        <div class="note-row reply-row">
            <div class="col-1 last">
                <div class="box">
                    <div class="box-title">
                        <strong><?php echo $this->getUser()->getName(); ?></strong>
                    </div>
                    <div class="box-date">
                        <?php /*echo $this->getDateDiff($_ticket->getCreatedAt(), $this->__('reported'));*/ ?>
                    </div>
                </div>
            </div>
            <div class="col-2 last">
                <form class="box-note reply-box">
                    <input type="text" id="ticket_reply_message" class="reply not-active" name="reply"
                           value="<?php echo $this->__('Click here to reply to this ticket'); ?>"/>
                    <div class="text-right">
                        <button type="button" title="<?php echo $this->__('Send') ?>"
                                id="ticket_send_button" class="btn btn-primary btn-send-ticket">
                            <span><span><?php echo $this->__('Send') ?></span></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="buttons-set">
        <p class="back-link">
            <a href="<?php echo $this->escapeUrl($this->getBackUrl()); ?>">
                <small>&laquo; </small><?php echo $this->getBackTitle(); ?>
            </a>
        </p>
    </div>
</div>
<script type="text/javascript">
    new Freshdesk.Account.Ticket.View.Reply(
        'ticket_reply_message',
        'ticket_reply_button',
        'ticket_send_button',
        '<?php echo $this->__('Click here to reply to this ticket'); ?>',
        'not-active',
        '<?php echo $this->getSendReplyUrl(); ?>',
        '<?php echo $this->getMessageTag(); ?>'

    );
</script>